In [52]:
# Import Libraries

import pandas as pd
import numpy as np
from functools import reduce

# Task 1: Create a DataFrame using Pandas
## Create a DataFrame with the following data:
### Name: Alice, Bob, Charlie, David
### Age: 25, 30, 35, 28
### City: New York, San Francisco, Los Angeles, Chicago

In [2]:
# Create Dataframe
data1 = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']
}
df1 = pd.DataFrame(data1)
df1

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   28        Chicago


# Task 2: Row and Column Manipulation
## Drop the 'City' column from the DataFrame created in Task 1

In [4]:
# Drop city column
drop_df1 = df1.drop('City', axis=1)
drop_df1

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   28

# Task 3: Handling Null Values
## Create a new DataFrame with some null values and fill them

In [6]:
# Create a new DataFrame with some null values
data3 = {
'A': [1, 2, None, 4],
'B': [5, None, 7, 8],
'C': [None, 10, 11, 12]
}
df3 = pd.DataFrame(data3)
df3

     A    B     C
0  1.0  5.0   NaN
1  2.0  NaN  10.0
2  NaN  7.0  11.0
3  4.0  8.0  12.0

In [7]:
# Missing null values

df3.isnull().sum()

A    1
B    1
C    1
dtype: int64

In [8]:
# Fill missing values
fillna_df3 = df3.fillna(0)
fillna_df3

     A    B     C
0  1.0  5.0   0.0
1  2.0  0.0  10.0
2  0.0  7.0  11.0
3  4.0  8.0  12.0

# Task 4: GroupBy and Describe
## Using the following DataFrame, group by 'Category' and describe the 'Value' column

In [9]:
df_group = pd.DataFrame({
    'Category': ['A', 'B', 'A', 'B', 'A', 'C'],
    'Value': [10, 20, 15, 25, 30, 35]
})
df_group

  Category  Value
0        A     10
1        B     20
2        A     15
3        B     25
4        A     30
5        C     35

In [10]:
# Groupby and Describe
df_group.groupby('Category')['Value'].describe()

          count       mean        std   min    25%   50%    75%   max
Category
A           3.0  18.333333  10.408330  10.0  12.50  15.0  22.50  30.0
B           2.0  22.500000   3.535534  20.0  21.25  22.5  23.75  25.0
C           1.0  35.000000        NaN  35.0  35.00  35.0  35.00  35.0

# Task 5: Concatenation and Merging
## Concatenate two DataFrames vertically and merge them horizontally

In [14]:
# Given:

df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})
df3 = pd.DataFrame({'C': [9, 10], 'D': [11, 12]})

con_df = pd.concat([df1, df2, df3], axis=1)
con_df

   A  B  A  B   C   D
0  1  3  5  7   9  11
1  2  4  6  8  10  12

# Task 6: Tuples and Sets
## Create a tuple of fruits and a set of numbers.
## Then, try to add an element to each and observe the difference.

In [18]:
# Tuple of fruits
fruits = ('apple', 'banana', 'cherry', 'date', 'grape')

# Set of numbers
numbers = {5, 6, 7, 8, 9}

In [16]:
# Add to the set
numbers.add(10)
numbers

{5, 6, 7, 8, 9, 10}

In [17]:
# Add to fruits
try:
    fruits.add('kiwi')
except AttributeError as e:
    print(f"Error: {e}")

Error: 'tuple' object has no attribute 'add'

# Task 7: Dictionaries
## Create a dictionary of student names and their scores.
## Then, update a student's score and add a new student.

In [19]:
# Create a dictionary of student names and their scores
students = {
    'Alice': 90,
    'Bob': 85,
    'Charlie': 92,
    'David': 78
}
students

{'Alice': 90, 'Bob': 85, 'Charlie': 92, 'David': 78}

In [20]:
# update a student's score and add a new student
students['Bob'] = 88
students['Eve'] = 95
students

{'Alice': 90, 'Bob': 88, 'Charlie': 92, 'David': 78, 'Eve': 95}

# Task 8: Functions and Lambda
## Create a function to calculate the square of a number.
## Then, use a lambda function to do the same.

In [22]:
#  Create a function to calculate the square of a number.
def square(x):
    return x**2
square(5)

25

In [23]:
# Using Lambda Create a function to calculate the square of a number.
Fnctn = lambda x: x**2
Fnctn(5)

25

# Task 9: Iterators and Generators
## Create an iterator for the first 5 even numbers.
## Then, create a generator for the same.

In [25]:
# Create an iterator for the first 5 even numbers
class EvenNumberIterator:
    def __init__(self):
        self._data = [0, 2, 4, 6, 8]
        self._index = 0

    def __iter__(self):
        return self

    def __next__(self):
        if self._index < len(self._data):
            result = self._data[self._index]
            self._index += 1
            return result
        else:
            raise StopIteration

even_iter = EvenNumberIterator()
for num in even_iter:
    print(num)

0
2
4
6
8

In [28]:
# create a generator for the same.
def even_number_generator():
    num = 0
    while True:
        yield num
        num += 2
        if num > 8:
            break

even_gen = even_number_generator()
for num in even_gen:
    print(num)

0
2
4
6
8

# Task 10: Map, Reduce, and Filter
## Use map to square all numbers in a list.
## Use reduce to find the product of all numbers in a list.
## Use filter to get only even numbers from a list.

numbers = [1, 2, 3, 4, 5]

In [41]:
# Use map to square all numbers in a list.

numbers = [1, 2, 3, 4, 5]
squared_numbers = list(map(lambda x: x**2, numbers))
squared_numbers

[1, 4, 9, 16, 25]

In [42]:
# Use reduce to find the product of all numbers in a list.
from functools import reduce
product = reduce(lambda x, y: x*y, numbers)
product

120

In [43]:
# Use filter to get only even numbers from a list.
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
even_numbers

[2, 4]

# Task 11: Object-Oriented Programming - Creating a Class
## Create a class called 'Rectangle' with attributes 'length' and 'width'.
## Include methods to calculate area and perimeter.

In [49]:
# Include methods to calculate area and perimeter.
class Rectangle:
    def __init__(self, length, width):
        self.length = length
        self.width = width

    def area(self):
        return self.length * self.width

    def perimeter(self):
        return 2 * (self.length + self.width)

rect = Rectangle(5, 3)
print("Area:", rect.area())
print("Perimeter:", rect.perimeter())

Area: 15
Perimeter: 16

# Task 12: Pandas Data Analysis
## Using the following DataFrame, perform these tasks:
## 1. Find the average salary by department
## 2. Get the names of employees with salary > 60000
## 3. Add a new column 'Bonus' which is 10% of salary

In [30]:
df_employees = pd.DataFrame({
    'Name': ['John', 'Jane', 'Bob', 'Alice', 'Charlie'],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR'],
    'Salary': [55000, 65000, 70000, 60000, 58000]
})
df_employees

      Name Department  Salary
0     John         IT   55000
1     Jane         HR   65000
2      Bob         IT   70000
3    Alice    Finance   60000
4  Charlie         HR   58000

In [31]:
# Find the average salary by department

averageSalary = df_employees.groupby('Department')['Salary'].mean()
averageSalary

Department
Finance    60000.0
HR         61500.0
IT         62500.0
Name: Salary, dtype: float64

In [38]:
# Get the names of employees with salary > 60000

employees_high_salary = df_employees[df_employees['Salary'] > 60000]
names_high_salary = employees_high_salary['Name']
print(names_high_salary)

1    Jane
2     Bob
Name: Name, dtype: object

In [40]:
# Add a new column 'Bonus' which is 10% of salary
df_employees['Bonus'] = df_employees['Salary'] * 0.1
df_employees

      Name Department  Salary   Bonus
0     John         IT   55000  5500.0
1     Jane         HR   65000  6500.0
2      Bob         IT   70000  7000.0
3    Alice    Finance   60000  6000.0
4  Charlie         HR   58000  5800.0